//
// Created by Admin on 10/21/2025.
//

#ifndef THINGPROPERTIES_H
#define THINGPROPERTIES_H

// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5a6d58a8-d8e7-4d9d-94ad-3d3c4353c1f5";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLocalPressureChange();
void onLocalTempChange();
void onAirQualityChange();

String webData;
float localPressure;
float localTemp;
int airQuality;

void initProperties(){

    ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
    ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
    ArduinoCloud.addProperty(webData, READ, ON_CHANGE, NULL);
    ArduinoCloud.addProperty(localPressure, READWRITE, 2 * SECONDS, onLocalPressureChange);
    ArduinoCloud.addProperty(localTemp, READWRITE, 2 * SECONDS, onLocalTempChange);
    ArduinoCloud.addProperty(airQuality, READWRITE, ON_CHANGE, onAirQualityChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);


#endif //THINGPROPERTIES_H
